assets/all-assets.svg
assets/all-assets.txt
assets/change_dpi.sh
assets/sed.sh
assets/unsed.sh
gtk-3.0/assets/change_dpi.sh
gtk-3.0/assets/sed.sh
gtk-3.0/assets/unsed.sh
gtk-3.0/assets/all-assets.svg
gtk-3.0/assets/all-assets.txt