# Spaceship Prompt
SPACESHIP_TIME_SHOW=true
SPACESHIP_DIR_TRUNC_REPO=true
SPACESHIP_PROMPT_ORDER=(
  user           
  host           
  dir            
  git           
  hg           
  package        
  node           
  bun            
  deno           
  ruby           
  python         
  elm            
  elixir         
  xcode          
  swift          
  golang         
  perl           
  php            
  rust           
  haskell        
  scala          
  kotlin         
  java           
  lua            
  dart           
  julia          
  crystal        
  docker         
  docker_compose 
  aws            
  gcloud         
  azure          
  venv           
  conda          
  dotnet         
  ocaml          
  vlang          
  zig            
  purescript     
  erlang         
  kubectl        
  ansible        
  terraform      
  pulumi         
  ibmcloud       
  nix_shell      
  gnu_screen     
  async          
  line_sep       
  battery        
  jobs           
  exit_code      
  sudo           
  char           
)
SPACESHIP_RPROMPT_ORDER=(
  exec_time
  time
)
SPACESHIP_PROMPT_ADD_NEWLINE="true"
SPACESHIP_PROMPT_SEPARATE_LINE="true"
SPACESHIP_PROMPT_FIRST_PREFIX_SHOW="true"
SPACESHIP_RPROMPT_FIRST_PREFIX_SHOW="true"
SPACESHIP_NODE_PREFIX=""
SPACESHIP_USER_COLOR="green"
SPACESHIP_USER_COLOR_ROOT="red"
SPACESHIP_USER_SHOW="true"
SPACESHIP_USER_PREFIX="["
SPACESHIP_USER_SUFFIX="]"
SPACESHIP_DIR_PREFIX="%F{81} %f"
SPACESHIP_DIR_COLOR="cyan"
SPACESHIP_GIT_BRANCH_COLOR="blue"
SPACESHIP_GIT_PREFIX=""
SPACESHIP_GIT_STATUS_COLOR="blue"
SPACESHIP_GIT_STATUS_PREFIX="·["
SPACESHIP_GIT_STATUS_DELETED=""
SPACESHIP_HOST_SHOW="true"
SPACESHIP_HOST_PREFIX="@"
SPACESHIP_HOST_SUFFIX=":"
SPACESHIP_HOST_COLOR_SSH="magenta"
SPACESHIP_EXEC_TIME_ELAPSED="0"
SPACESHIP_EXEC_TIME_PRECISION="1"
SPACESHIP_EXEC_TIME_SHOW="true"
SPACESHIP_EXEC_TIME_PREFIX="%F{222}( %f"
SPACESHIP_EXEC_TIME_SUFFIX="%F{222}) %f"
SPACESHIP_EXEC_TIME_COLOR="#f7c67f"
SPACESHIP_TIME_12HR="false"
SPACESHIP_TIME_PREFIX=""
SPACESHIP_TIME_COLOR="#a48cf2"
SPACESHIP_CHAR_SYMBOL=" "
SPACESHIP_CHAR_SYMBOL_ROOT=""
SPACESHIP_CHAR_COLOR_SUCCESS="green"
SPACESHIP_CHAR_COLOR_FAILURE="red"
SPACESHIP_CHAR_COLOR_SECONDARY="cyan"

