# class                  title     bg    text   indicator  border
client.focused           $cyan     $bg   $text  $cyan      $cyan
client.focused_inactive  $blue     $bg   $blue  $fg        $blue
client.unfocused         $blue     $bg   $blue  $fg        $blue
client.urgent            $red      $bg   $red   $fg        $red
client.placeholder       $fg       $bg   $text  $fg        $fg
client.background        $bg

# bar
bar {
  colors {
    background         $bg
    statusline         $text
    focused_statusline $text
    focused_separator  $bg

    # target           border bg        text
    focused_workspace  $bg    $cyan     $fg
    active_workspace   $bg    $fg       $text
    inactive_workspace $bg    $fg       $text
    urgent_workspace   $bg    $red      $fg
  }
}
